package dev.ujhhgtg.wekit.extensions.monet

internal data class MonetSemanticRule(
    val id: String,
    val type: String,
    val requiredEvidence: Set<String>,
    val requiredDexEvidence: Set<String> = emptySet(),
    val requiredAdjacentRoles: Map<Int, String> = emptyMap(),
    val preferredEvidence: Set<String> = emptySet(),
    val optional: Boolean = false,
)

internal val MONET_RULES = listOf(
    MonetSemanticRule("about.authors.suffix", "string", setOf("config::text:《隐私保护指引》", "context:layout:attribute:LinearLayout/LinearLayout/LinearLayout/TextView:16842968:paddingRight:REFERENCE:reference:dimen:REFERENCE")),
    MonetSemanticRule("about.compatibility", "string", setOf("config::text:ICP备案号：粤B2-20090059-1621A >")),
    MonetSemanticRule("about.separator", "string", setOf("config::text:客服电话：400 670 0700")),
    MonetSemanticRule("about.slogan", "string", setOf("config::text:腾讯公司 版权所有\nCopyright © 2011-%d Tencent. All Rights Reserved.")),
    MonetSemanticRule("about.title", "string", setOf("config::text:《软件许可及服务协议》")),
    MonetSemanticRule("about.update-date", "string", setOf("config::text:算法备案信息 >")),
    MonetSemanticRule("brand.circular.background", "drawable", setOf("attribute:shape/solid:16843173:color:COLOR_ARGB8:literal:COLOR_ARGB8:1278791039", "usage:layout:FrameLayout/FrameLayout/View:16842964:background")),
    MonetSemanticRule("chat.brand-action.background", "drawable", setOf("usage:layout:LinearLayout/com.tencent.mm.plugin.game.ui.GameMessageBubbleView/LinearLayout:16842964:background")),
    MonetSemanticRule("chat.bubble.incoming.link", "drawable", setOf("usage:layout:LinearLayout/LinearLayout/LinearLayout/LinearLayout/com.tencent.mm.ui.chatting.viewitems.mvvmview.ChattingFileMvvmView:16842964:background", "usage:layout:LinearLayout:16842964:background")),
    MonetSemanticRule("chat.bubble.incoming.link.mask", "drawable", setOf("usage:layout:LinearLayout/LinearLayout/LinearLayout/LinearLayout/LinearLayout/FrameLayout/ImageView:16842964:background")),
    MonetSemanticRule("chat.bubble.incoming.normal", "drawable", setOf("usage:layout:LinearLayout/LinearLayout/RelativeLayout/com.tencent.mm.ui.widget.MMNeat7extView:16842964:background")),
    MonetSemanticRule("chat.bubble.outgoing.link", "drawable", setOf("usage:layout:LinearLayout/RelativeLayout/LinearLayout/FrameLayout/LinearLayout:16842964:background")),
    MonetSemanticRule("chat.bubble.outgoing.link.mask", "drawable", setOf("usage:layout:LinearLayout/RelativeLayout/LinearLayout/FrameLayout/ImageView:16842964:background")),
    MonetSemanticRule("chat.bubble.outgoing.normal", "drawable", setOf("usage:layout:LinearLayout/LinearLayout/LinearLayout/LinearLayout/com.tencent.mm.ui.widget.MMNeat7extView:16842964:background")),
    MonetSemanticRule("chat.input.background", "drawable", setOf("usage:layout:RelativeLayout/LinearLayout/LinearLayout/LinearLayout/LinearLayout/LinearLayout/RelativeLayout/com.tencent.mm.view.MaxHeightScrollView/LinearLayout/LinearLayout:16842964:background")),
    MonetSemanticRule("chat.input.container", "layout", setOf("attribute:RelativeLayout/LinearLayout/RelativeLayout:16842997:layout_height:DIMENSION:literal:DIMENSION:12289")),
    MonetSemanticRule("chat.input.transparent-layer", "drawable", setOf("usage:layout:LinearLayout/FrameLayout/LinearLayout/LinearLayout/RelativeLayout/FrameLayout/com.tencent.mm.ui.widget.RoundedCornerFrameLayout/View:16842964:background")),
    MonetSemanticRule("chat.quote.background", "drawable", setOf("usage:layout:RelativeLayout/LinearLayout/LinearLayout/LinearLayout/androidx.constraintlayout.widget.ConstraintLayout/RelativeLayout:16842964:background")),
    MonetSemanticRule("chat.red-envelope.incoming.normal", "drawable", setOf("usage:layout:LinearLayout/LinearLayout/LinearLayout:16842964:background", "usage:layout:LinearLayout/LinearLayout/RelativeLayout/FrameLayout:16842964:background")),
    MonetSemanticRule("chat.red-envelope.outgoing.normal", "drawable", setOf("usage:layout:LinearLayout/LinearLayout:16842964:background", "usage:layout:LinearLayout/RelativeLayout/FrameLayout:16842964:background")),
    MonetSemanticRule("chat.voice-to-text.background", "drawable", setOf("usage:layout:com.tencent.mm.ui.chatting.viewitems.ChattingItemTranslate:16842964:background")),
    MonetSemanticRule("launcher.splash.background", "drawable", setOf("attribute:layer-list:16843550:opacity:DEC:literal:DEC:4294967295")),
    MonetSemanticRule("launcher.themed.icon", "mipmap", setOf("incoming:mipmap")),
    MonetSemanticRule("main.tab.background", "color", setOf("config::literal:COLOR_ARGB8:3522623222")),
    MonetSemanticRule("payment.key.primary", "drawable", setOf("usage:layout:merge/LinearLayout/androidx.gridlayout.widget.GridLayout/com.tencent.mm.wallet_core.ui.WalletTextView:16842964:background")),
    MonetSemanticRule("payment.key.secondary", "drawable", setOf("attribute:selector/item/shape/solid:16843173:color:COLOR_RGB8:literal:COLOR_RGB8:4278340902")),
    MonetSemanticRule("payment.keyboard.key.style", "style", setOf("usage:layout:merge/LinearLayout/androidx.gridlayout.widget.GridLayout/com.tencent.mm.wallet_core.ui.WalletTextView:null:style")),
    MonetSemanticRule("theme.color.10000000--10ffffff.slot-02", "color", setOf("config:-night:literal:COLOR_RGB8:4281348144", "config::literal:COLOR_RGB8:4293256677")),
    MonetSemanticRule("theme.color.10000000--10ffffff.slot-03", "color", setOf("config:-night:literal:COLOR_RGB8:4280558628", "config::literal:COLOR_RGB8:4293256677")),
    MonetSemanticRule("theme.color.10000000--10ffffff.slot-04", "color", setOf("config:-night:literal:COLOR_RGB8:4280295456", "config::literal:COLOR_RGB8:4293256677")),
    MonetSemanticRule("theme.color.10000000--system-surface-container-dark.slot-01", "color", setOf("usage:layout:com.tencent.mm.plugin.finder.view.FinderInterceptFrameLayout/LinearLayout/View:16842964:background")),
    MonetSemanticRule("theme.color.system-accent1-100--system-accent1-800.slot-01", "color", setOf("config::literal:COLOR_ARGB8:4290047182", "incoming:color")),
    MonetSemanticRule("theme.color.system-accent1-300--system-accent1-400.slot-01", "color", setOf("usage:layout:RelativeLayout/com.tencent.mm.ui.base.MMAutoSizeTextView:16842904:textColor")),
    MonetSemanticRule("theme.color.system-accent1-300--system-accent1-400.slot-05", "color", setOf("config::literal:COLOR_RGB8:4288015465")),
    MonetSemanticRule("theme.color.system-accent1-300--system-accent1-400.slot-08", "color", setOf("config::literal:COLOR_ARGB8:4292954441", "incoming:color")),
    MonetSemanticRule("theme.color.system-accent1-300--system-accent1-400.slot-10", "color", setOf("usage:layout:RelativeLayout/LinearLayout/RelativeLayout/EditText:16842904:textColor")),
    MonetSemanticRule("theme.color.system-accent2-600--system-accent2-600.slot-01", "color", setOf("usage:layout:merge/com.tencent.mm.plugin.ball.view.FloatBallRoundCornerFrameLayout/View:16842964:background")),
    MonetSemanticRule("theme.color.system-primary-light--system-primary-dark.slot-01", "color", setOf("usage:drawable:rotate/shape/gradient:16843166:endColor")),
    MonetSemanticRule("theme.color.system-primary-light--system-primary-dark.slot-02", "color", setOf("usage:layout:FrameLayout/com.tencent.mm.ui.widget.RoundedCornerFrameLayout/LinearLayout/androidx.constraintlayout.widget.ConstraintLayout/com.tencent.mm.ui.widget.RoundedCornerFrameLayout:16842964:background")),
    MonetSemanticRule("theme.color.system-primary-light--system-primary-dark.slot-03", "color", setOf("config::literal:COLOR_ARGB8:4278290754")),
    MonetSemanticRule("theme.color.system-primary-light--system-primary-dark.slot-04", "color", setOf("config::literal:COLOR_ARGB8:4281912703", "incoming:drawable")),
    MonetSemanticRule("theme.color.system-primary-light--system-primary-dark.slot-06", "color", setOf("config::literal:COLOR_ARGB8:4278557260", "incoming:drawable")),
    MonetSemanticRule("theme.color.system-primary-light--system-primary-dark.slot-08", "color", setOf("config::literal:COLOR_ARGB8:4280987239", "incoming:style")),
    MonetSemanticRule("theme.color.system-primary-light--system-primary-dark.slot-10", "color", setOf("config::literal:COLOR_ARGB8:4282299765", "incoming:layout")),
    MonetSemanticRule("theme.color.system-primary-light--system-primary-dark.slot-13", "color", setOf("usage:layout:LinearLayout/TextView:16842907:textColorLink")),
    MonetSemanticRule("theme.color.system-primary-light--system-primary-dark.slot-14", "color", setOf("config:-night:literal:COLOR_ARGB8:4292798975", "incoming:layout")),
    MonetSemanticRule("theme.color.system-primary-light--system-primary-dark.slot-16", "color", setOf("usage:layout:LinearLayout/LinearLayout/com.tencent.mm.ui.widget.RoundCornerLinearLayout/TextView:16842904:textColor")),
    MonetSemanticRule("theme.color.system-primary-light--system-primary-dark.slot-18", "color", setOf("usage:layout:LinearLayout/RelativeLayout/com.tencent.mm.ui.widget.MMRoundCornerImageView:16842964:background")),
    MonetSemanticRule("theme.color.system-primary-light--system-primary-dark.slot-22", "color", setOf("config::literal:COLOR_ARGB8:3439295252")),
    MonetSemanticRule("theme.color.system-primary-light--system-primary-dark.slot-24", "color", setOf("config::literal:COLOR_ARGB8:4076863487")),
    MonetSemanticRule("theme.color.system-primary-light--system-primary-dark.slot-26", "color", setOf("config::literal:COLOR_RGB8:4293309565")),
    MonetSemanticRule("theme.color.system-primary-light--system-primary-dark.slot-27", "color", setOf("config::literal:COLOR_RGB8:4294917694")),
    MonetSemanticRule("theme.color.system-surface-container-dark--system-surface-container-dark.slot-01", "color", setOf("config:-night:literal:COLOR_RGB8:4284506208", "config::literal:COLOR_RGB8:4283190348")),
    MonetSemanticRule("theme.color.system-surface-container-dark--system-surface-container-dark.slot-02", "color", setOf("usage:layout:com.tencent.mm.view.HardTouchableLayout/LinearLayout/FrameLayout/TextView:16842904:textColor")),
    MonetSemanticRule("theme.color.system-surface-container-dark--system-surface-container-dark.slot-03", "color", setOf("usage:layout:com.tencent.mm.plugin.finder.live.view.FinderLiveListHorizontalContainer:16842964:background")),
    MonetSemanticRule("theme.color.system-surface-container-dark--system-surface-container-dark.slot-05", "color", setOf("config::literal:COLOR_RGB8:4288327124")),
    MonetSemanticRule("theme.color.system-surface-container-dark--system-surface-container-dark.slot-06", "color", setOf("config::literal:COLOR_RGB8:4292953916")),
    MonetSemanticRule("theme.color.system-surface-container-dark--system-surface-container-dark.slot-09", "color", setOf("config::literal:COLOR_ARGB8:2147483648", "usage:layout:FrameLayout/LinearLayout/RelativeLayout/TextView:16842904:textColor")),
    MonetSemanticRule("theme.color.system-surface-container-dark--system-surface-container-dark.slot-10", "color", setOf("context:layout:attribute:FrameLayout/LinearLayout/TextView:16842972:visibility:DEC:literal:DEC:0")),
    MonetSemanticRule("theme.color.system-surface-container-dark--system-surface-container-dark.slot-12", "color", setOf("usage:layout:RelativeLayout/androidx.coordinatorlayout.widget.CoordinatorLayout:16842964:background")),
    MonetSemanticRule("theme.color.system-surface-container-dark--system-surface-container-dark.slot-15", "color", setOf("config::literal:COLOR_RGB8:4278212427")),
    MonetSemanticRule("theme.color.system-surface-container-dark--system-surface-container-dark.slot-16", "color", setOf("config::literal:COLOR_ARGB8:4283190348", "context:drawable:attribute:shape/corners:16843176:radius:DIMENSION:literal:DIMENSION:4097")),
    MonetSemanticRule("theme.color.system-surface-container-dark--system-surface-container-dark.slot-18", "color", setOf("config::literal:COLOR_RGB8:4279505439")),
    MonetSemanticRule("theme.color.system-surface-container-dark--system-surface-container-dark.slot-19", "color", setOf("config::literal:COLOR_RGB8:4280689210")),
    MonetSemanticRule("theme.color.system-surface-container-dark--system-surface-container-dark.slot-21", "color", setOf("config::literal:COLOR_ARGB8:234881023", "usage:layout:LinearLayout/FrameLayout:16842964:background")),
    MonetSemanticRule("theme.color.system-surface-container-dark--system-surface-container-dark.slot-22", "color", setOf("config::literal:COLOR_ARGB8:864585864")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-01", "color", setOf("config::literal:COLOR_ARGB8:1307438573")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-02", "color", setOf("usage:layout:com.tencent.mm.plugin.finder.view.FinderInterceptFrameLayout/LinearLayout/TextView:16842964:background")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-04", "color", setOf("usage:layout:FrameLayout/ScrollView/LinearLayout/com.tencent.mm.ui.widget.InputPanelFrameLayout/LinearLayout/com.tencent.mm.ui.widget.RoundedCornerFrameLayout:16842964:background")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-05", "color", setOf("context:layout:attribute:LinearLayout/RelativeLayout/LinearLayout/View:16842997:layout_height:DIMENSION:literal:DIMENSION:2049", "context:layout:attribute:RelativeLayout/ScrollView/LinearLayout/LinearLayout:16843002:layout_marginBottom:DIMENSION:literal:DIMENSION:4097", "usage:layout:RelativeLayout:16842964:background")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-07", "color", setOf("config::literal:COLOR_RGB8:4293783021", "usage:layout:LinearLayout/TextView:16842964:background")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-08", "color", setOf("config::literal:COLOR_ARGB8:4281874488")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-14", "color", setOf("usage:layout:merge/com.tencent.mm.plugin.finder.view.FinderCommentFooter/LinearLayout:16842964:background")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-15", "color", setOf("config:-night:literal:COLOR_RGB8:4281874488", "config::literal:COLOR_RGB8:4294440951")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-17", "color", setOf("config::literal:COLOR_RGB8:4287935452")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-23", "color", setOf("config::literal:COLOR_RGB8:4280953387")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-25", "color", setOf("config::literal:COLOR_ARGB8:2130706432", "usage:owner:style:item:16843857:reference")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-26", "color", emptySet()),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-27", "color", setOf("config::literal:COLOR_RGB8:4280492835")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-29", "color", setOf("usage:layout:FrameLayout/com.tencent.mm.ui.widget.RoundedCornerFrameLayout/LinearLayout/com.tencent.mm.ui.widget.RoundedCornerFrameLayout:16842964:background")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-30", "color", setOf("config::literal:COLOR_RGB8:4294967295", "usage:layout:LinearLayout/RelativeLayout:16842964:background")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-33", "color", setOf("config:-night:literal:COLOR_RGB8:4283256141")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-34", "color", setOf("config:-night:literal:COLOR_RGB8:4279834905", "config::literal:COLOR_RGB8:4294111986")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-35", "color", setOf("config:-night:literal:COLOR_RGB8:4280558628", "config::literal:COLOR_RGB8:4294111986")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-36", "color", setOf("config::literal:COLOR_ARGB8:4294111986")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-38", "color", setOf("usage:layout:LinearLayout/FrameLayout/ScrollView:16842964:background")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-40", "color", setOf("usage:drawable:selector/item/rotate/rotate/shape/solid:16843173:color")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-42", "color", emptySet()),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-43", "color", setOf("config::literal:COLOR_RGB8:4292927712", "incoming:color")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-45", "color", setOf("usage:layout:com.tencent.mm.plugin.sns.ui.item.improve.view.ImproveRoundLinearLayout/com.tencent.mm.plugin.sns.ui.item.improve.view.ImproveRoundLinearLayout/FrameLayout/com.tencent.mm.view.CropImageView:16843033:src")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-51", "color", setOf("config:-night:literal:COLOR_RGB8:4279308561", "config::literal:COLOR_RGB8:4294111986")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-52", "color", setOf("config:-watch:literal:COLOR_ARGB8:3741319167", "config::literal:COLOR_ARGB8:3724541952")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-54", "color", setOf("config:-night:literal:COLOR_ARGB8:234881023", "config::literal:COLOR_RGB8:4293783021")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-light.slot-01", "color", setOf("config:-night:literal:COLOR_ARGB8:3439329279", "config::reference:color:REFERENCE")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-light.slot-05", "color", setOf("config::literal:COLOR_ARGB8:1275068416", "usage:layout:RelativeLayout:16842964:background")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-light.slot-06", "color", setOf("config::literal:COLOR_ARGB8:3438145005")),
    MonetSemanticRule("theme.color.system-surface-dark--system-surface-container-dark", "color", setOf("usage:layout:RelativeLayout/com.tencent.mm.plugin.finder.live.widget.FinderLiveViewBottomSheetPanel:16842964:background")),
    MonetSemanticRule("theme.color.system-surface-dark--system-surface-dark.slot-01", "color", setOf("usage:layout:com.tencent.mm.ui.widget.RoundCornerRelativeLayout/TextView:16842964:background")),
    MonetSemanticRule("theme.color.system-surface-dark--system-surface-dark.slot-03", "color", setOf("config::literal:COLOR_ARGB8:4281545523")),
    MonetSemanticRule("theme.color.system-surface-dark--system-surface-dark.slot-05", "color", setOf("config::literal:COLOR_ARGB8:1291845631", "usage:layout:LinearLayout/RelativeLayout/com.tencent.mm.ui.widget.MMTextView:16842904:textColor")),
    MonetSemanticRule("theme.color.system-surface-dark--system-surface-dark.slot-06", "color", setOf("config::literal:COLOR_RGB8:4279834905", "usage:layout:RelativeLayout/RelativeLayout/ImageView:16842964:background")),
    MonetSemanticRule("theme.color.system-surface-dark--system-surface-dark.slot-08", "color", setOf("config::literal:COLOR_RGB8:4279834905", "usage:layout:RelativeLayout/LinearLayout/LinearLayout:16842964:background")),
    MonetSemanticRule("theme.color.system-surface-dark--system-surface-dark.slot-10", "color", setOf("config::literal:COLOR_ARGB8:4284900966")),
    MonetSemanticRule("theme.color.system-surface-dark--system-surface-dark.slot-11", "color", setOf("config::literal:COLOR_RGB8:4287137928", "usage:layout:LinearLayout/LinearLayout/LinearLayout/TextView:16842904:textColor")),
    MonetSemanticRule("theme.color.system-surface-light--system-surface-dark.slot-01", "color", setOf("usage:drawable:selector/item/shape/gradient:16843275:centerColor")),
    MonetSemanticRule("theme.color.system-surface-light--system-surface-dark.slot-02", "color", setOf("usage:layout:RelativeLayout/RelativeLayout/LinearLayout/com.tencent.mm.plugin.textstatus.ui.MediumBoldTextView:16842904:textColor")),
    MonetSemanticRule("theme.color.system-surface-light--system-surface-dark.slot-03", "color", setOf("usage:layout:com.tencent.mm.plugin.finder.video.FinderFeedNewSeekBarLayout/TextView:16842904:textColor")),
    MonetSemanticRule("theme.color.system-surface-light--system-surface-dark.slot-06", "color", setOf("usage:layout:FrameLayout/com.tencent.mm.plugin.game.ui.GameBestSellingItemView/RelativeLayout/TextView:16842904:textColor")),
    MonetSemanticRule("theme.color.system-surface-light--system-surface-dark.slot-08", "color", setOf("usage:layout:com.tencent.mm.plugin.appbrand.widget.recyclerview.LoadMoreRecyclerView:16842964:background")),
    MonetSemanticRule("theme.color.system-surface-light--system-surface-dark.slot-10", "color", setOf("usage:drawable:layer-list/item/shape/gradient:16843275:centerColor")),
    MonetSemanticRule("theme.color.system-surface-light--system-surface-light.slot-01", "color", setOf("usage:layout:com.tencent.mm.view.HardTouchableLayout/RelativeLayout/androidx.coordinatorlayout.widget.CoordinatorLayout/com.google.android.material.appbar.AppBarLayout/LinearLayout/LinearLayout/com.tencent.mm.plugin.finder.view.FinderTagFlowLayout/TextView:16842904:textColor")),
    MonetSemanticRule("theme.color.system-surface-light--system-surface-light.slot-03", "color", setOf("usage:layout:com.tencent.mm.ui.widget.RoundCornerLinearLayout/com.tencent.neattextview.textview.view.NeatTextView:16842904:textColor")),
    MonetSemanticRule("theme.color.unknown--10ffffff.slot-01", "color", setOf("config::literal:COLOR_RGB8:4292532954")),
    MonetSemanticRule("theme.color.unknown--10ffffff.slot-04", "color", setOf("config:-night:literal:COLOR_RGB8:4280295456", "config::literal:COLOR_RGB8:4294967295")),
    MonetSemanticRule("theme.color.unknown--10ffffff.slot-06", "color", setOf("context:layout:attribute:RelativeLayout/ListView:16842974:scrollbars:HEX:literal:HEX:512", "context:layout:attribute:RelativeLayout/com.tencent.mm.ui.widget.button.WeButton:16842972:visibility:DEC:literal:DEC:2", "context:layout:attribute:RelativeLayout/ListView:16842970:focusable:BOOLEAN:literal:BOOLEAN:0")),
    MonetSemanticRule("theme.color.unknown--10ffffff.slot-07", "color", setOf("config:-night:literal:COLOR_RGB8:4281348144", "config::reference:color:REFERENCE")),
    MonetSemanticRule("theme.color.unknown--10ffffff.slot-08", "color", setOf("config::literal:COLOR_RGB8:4294177779")),
    MonetSemanticRule("theme.color.unknown--10ffffff.slot-09", "color", setOf("config:-night:literal:COLOR_ARGB8:1291845632", "config::literal:COLOR_ARGB8:218103808")),
    MonetSemanticRule("theme.color.unknown--e6ffffff", "color", setOf("usage:layout:RelativeLayout/LinearLayout/LinearLayout/LinearLayout/com.tencent.mm.ui.widget.MMNeat7extView:16842904:textColor")),
    MonetSemanticRule("theme.color.unknown--system-primary-dark", "color", setOf("config:-night:literal:COLOR_RGB8:4281815170")),
    MonetSemanticRule("theme.color.unknown--system-surface-container-dark.slot-01", "color", setOf("config::literal:COLOR_RGB8:4284637796")),
    MonetSemanticRule("theme.color.unknown--system-surface-container-dark.slot-02", "color", setOf("usage:layout:LinearLayout/ScrollView/com.tencent.mm.ui.widget.InputPanelLinearLayout/Button:16842904:textColor")),
    MonetSemanticRule("theme.color.unknown--system-surface-container-dark.slot-03", "color", setOf("config:-night:literal:COLOR_RGB8:4280558628", "usage:drawable:layer-list/item/shape/solid:16843173:color")),
    MonetSemanticRule("theme.color.unknown--system-surface-container-dark.slot-04", "color", setOf("usage:layout:androidx.constraintlayout.widget.ConstraintLayout/com.tencent.mm.mj_publisher.finder.widgets.RoundFrameLayout:16842964:background")),
    MonetSemanticRule("theme.color.unknown--system-surface-container-dark.slot-05", "color", setOf("config::literal:COLOR_ARGB8:822083583")),
    MonetSemanticRule("theme.color.unknown--system-surface-dark.slot-02", "color", setOf("config::literal:COLOR_RGB8:4294309365")),
    MonetSemanticRule("about.authors.prefix", "string", setOf("config::text:《隐私保护指引摘要》")),
    MonetSemanticRule("payment.key.pressed", "drawable", setOf("context:style:usage:layout:merge/LinearLayout/androidx.gridlayout.widget.GridLayout/com.tencent.mm.wallet_core.ui.WalletTextView:null:style")),
    MonetSemanticRule("theme.color.10000000--10ffffff.slot-01", "color", setOf("context:drawable:usage:layout:com.tencent.mm.plugin.finder.live.view.FinderMaxSizeLayout/RelativeLayout:16842964:background", "config::literal:COLOR_RGB8:4293256677")),
    MonetSemanticRule("theme.color.10000000--10ffffff.slot-05", "color", setOf("context:drawable:usage:layout:FrameLayout/LinearLayout/LinearLayout/TextView:16842964:background", "config::literal:COLOR_RGB8:4293256677")),
    MonetSemanticRule("theme.color.10000000--10ffffff.slot-06", "color", setOf("context:layout:attribute:LinearLayout/LinearLayout/ImageView:16842997:layout_height:DIMENSION:literal:DIMENSION:104857633", "usage:layout:LinearLayout/View:16842964:background")),
    MonetSemanticRule("theme.color.10000000--system-surface-container-dark.slot-02", "color", setOf("context:drawable:usage:layout:RelativeLayout/com.tencent.mm.ui.widget.InputPanelLinearLayout/LinearLayout/RelativeLayout/LinearLayout/Button:16842964:background", "context:drawable:attribute:selector/item/shape/corners:16843176:radius:DIMENSION:literal:DIMENSION:5121")),
    MonetSemanticRule("theme.color.system-primary-light--system-primary-dark.slot-12", "color", setOf("context:layout:element:RelativeLayout/ScrollView/com.tencent.mm.ui.widget.InputPanelLinearLayout/LinearLayout/LinearLayout/LinearLayout/View", "config::literal:COLOR_RGB8:4278698336")),
    MonetSemanticRule("theme.color.system-primary-light--system-primary-dark.slot-19", "color", setOf("context:layout:simple-attribute:LinearLayout/ConstraintLayout/WeImageView:16842931:layout_gravity:HEX:literal:HEX:19", "context:layout:simple-attribute:ScrollView/LinearLayout/TextView:16842901:textSize:DIMENSION:literal:DIMENSION:3585", "context:layout:simple-attribute:LinearLayout/WeImageView:16842931:layout_gravity:HEX:literal:HEX:16")),
    MonetSemanticRule("theme.color.system-surface-container-dark--system-surface-container-dark.slot-04", "color", setOf("context:drawable:usage:layout:FrameLayout/com.tencent.mm.ui.widget.RoundedCornerFrameLayout/com.tencent.mm.ui.widget.MMRoundCornerImageView:16842964:background")),
    MonetSemanticRule("theme.color.system-surface-container-dark--system-surface-container-dark.slot-11", "color", setOf("context:layout:attribute:LinearLayout/ImageView:16842997:layout_height:DIMENSION:literal:DIMENSION:22017", "context:layout:attribute:LinearLayout/LinearLayout/TextView:16842927:gravity:HEX:literal:HEX:5")),
    MonetSemanticRule("theme.color.system-surface-container-dark--system-surface-container-dark.slot-17", "color", setOf("context:layout:attribute:RelativeLayout/com.tencent.mm.plugin.appbrand.widget.recent.AppBrandTaskRadiusLayout:16842996:layout_width:REFERENCE:reference:dimen:REFERENCE", "config::literal:COLOR_ARGB8:1291845632")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-primary-dark", "color", setOf("context:color:usage:layout:LinearLayout/RelativeLayout/RelativeLayout/RelativeLayout/ImageView:16842964:background")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-09", "color", setOf("context:drawable:usage:layout:androidx.constraintlayout.widget.ConstraintLayout/RelativeLayout/LinearLayout:16842964:background")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-10", "color", setOf("context:drawable:usage:layout:androidx.constraintlayout.widget.ConstraintLayout/com.tencent.mm.plugin.finder.shopping.view.FinderLiveShoppingPanel/RelativeLayout/LinearLayout/RelativeLayout/FrameLayout:16842964:background")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-11", "color", setOf("context:layout:attribute:FrameLayout/LinearLayout/View:16842997:layout_height:DEC:literal:DEC:4294967294", "config::literal:COLOR_ARGB8:2164260863")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-18", "color", setOf("context:drawable:usage:layout:LinearLayout/EditText:16842964:background")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-19", "color", setOf("context:drawable:usage:layout:androidx.coordinatorlayout.widget.CoordinatorLayout/LinearLayout/androidx.core.widget.NestedScrollView/LinearLayout/LinearLayout:16842964:background")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-31", "color", setOf("config::literal:COLOR_RGB8:4293783021", "context:color:usage:drawable:shape/stroke:16843173:color")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-44", "color", setOf("context:color:config:-night:literal:COLOR_RGB8:4279834905")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-49", "color", setOf("context:drawable:attribute:selector/item/shape/solid:16843173:color:COLOR_ARGB8:literal:COLOR_ARGB8:536870912", "config::literal:COLOR_RGB8:4294111986")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-light.slot-03", "color", setOf("context:layout:attribute:LinearLayout/FrameLayout/FrameLayout/com.tencent.mm.ui.widget.imageview.WeImageView:16843558:rotation:FLOAT:literal:FLOAT:1119092736", "config::literal:COLOR_RGB8:4294440951")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-light.slot-04", "color", setOf("context:layout:element:RelativeLayout/com.tencent.mm.plugin.sns.ad.landingpage.component.view.AdLandingGeneralVideoWrapper", "context:layout:attribute:RelativeLayout/RelativeLayout/ImageView:16842999:layout_marginLeft:DIMENSION:literal:DIMENSION:2561")),
    MonetSemanticRule("theme.color.system-surface-dark--system-surface-dark.slot-09", "color", setOf("context:style:usage:layout:RelativeLayout/LinearLayout/LinearLayout/LinearLayout/LinearLayout/TextView:null:style")),
    MonetSemanticRule("theme.color.system-surface-dark--system-surface-dark.slot-12", "color", setOf("context:drawable:attribute:selector/item/shape/stroke:16843097:width:DIMENSION:literal:DIMENSION:256", "context:layout:attribute:RelativeLayout/LinearLayout/ImageView:16843001:layout_marginRight:REFERENCE:reference:dimen:REFERENCE")),
    MonetSemanticRule("theme.color.system-surface-dark--system-surface-dark.slot-13", "color", setOf("context:layout:attribute:LinearLayout/LinearLayout/LinearLayout/com.tencent.mm.ui.widget.imageview.WeImageView:16843001:layout_marginRight:DIMENSION:literal:DIMENSION:2049", "config::literal:COLOR_ARGB8:3439329279")),
    MonetSemanticRule("theme.color.system-surface-light--system-surface-dark.slot-07", "color", setOf("context:drawable:usage:layout:com.tencent.mm.plugin.mv.ui.view.InterceptRelativeLayout/LinearLayout/LinearLayout/LinearLayout/LinearLayout/TextView:16842964:background")),
    MonetSemanticRule("theme.color.system-surface-light--system-surface-light.slot-04", "color", setOf("context:drawable:attribute:shape/corners:16843176:radius:DIMENSION:literal:DIMENSION:3585", "config:-night:reference:color:REFERENCE", "context:drawable:attribute:shape/size:16843097:width:REFERENCE:reference:dimen:REFERENCE")),
    MonetSemanticRule("theme.color.unknown--system-surface-dark.slot-01", "color", setOf("context:layout:attribute:ScrollView/LinearLayout/LinearLayout/TextView:16842904:textColor:COLOR_RGB8:literal:COLOR_RGB8:4280453922", "context:layout:attribute:LinearLayout/LinearLayout:16843002:layout_marginBottom:DIMENSION:literal:DIMENSION:4097")),
    MonetSemanticRule("theme.color.system-accent1-100--system-accent1-800.slot-02", "color", setOf("config::literal:COLOR_ARGB8:4290047182")),
    MonetSemanticRule("theme.color.system-accent1-100--system-accent1-800.slot-03", "color", setOf("config:-night:literal:COLOR_ARGB8:4280121928")),
    MonetSemanticRule("theme.color.system-accent1-100--system-accent1-800.slot-04", "color", setOf("config:-night:literal:COLOR_ARGB8:4280121928")),
    MonetSemanticRule("theme.color.system-accent1-300--system-accent1-400.slot-02", "color", setOf("config::literal:COLOR_ARGB8:4278627926")),
    MonetSemanticRule("theme.color.system-accent1-300--system-accent1-400.slot-03", "color", setOf("config::literal:COLOR_ARGB8:4280654940")),
    MonetSemanticRule("theme.color.system-accent1-300--system-accent1-400.slot-04", "color", setOf("config::literal:COLOR_ARGB8:4280654940")),
    MonetSemanticRule("theme.color.system-accent1-300--system-accent1-400.slot-06", "color", setOf("config::literal:COLOR_ARGB8:4288015465")),
    MonetSemanticRule("theme.color.system-accent1-300--system-accent1-400.slot-07", "color", setOf("config::literal:COLOR_ARGB8:4288015465")),
    MonetSemanticRule("theme.color.system-accent1-300--system-accent1-400.slot-09", "color", setOf("config::literal:COLOR_ARGB8:4292954441")),
    MonetSemanticRule("theme.color.system-primary-light--system-primary-dark.slot-05", "color", setOf("config:-night:literal:COLOR_ARGB8:4278557260")),
    MonetSemanticRule("theme.color.system-primary-light--system-primary-dark.slot-07", "color", setOf("config:-night:literal:COLOR_ARGB8:4281912703")),
    MonetSemanticRule("theme.color.system-primary-light--system-primary-dark.slot-09", "color", setOf("config::literal:COLOR_ARGB8:4280987239")),
    MonetSemanticRule("theme.color.system-primary-light--system-primary-dark.slot-11", "color", setOf("config:-night:literal:COLOR_ARGB8:4280654940")),
    MonetSemanticRule("theme.color.system-primary-light--system-primary-dark.slot-15", "color", setOf("config:-night:literal:COLOR_ARGB8:4292798975")),
    MonetSemanticRule("theme.color.system-primary-light--system-primary-dark.slot-17", "color", setOf("config:-night:literal:COLOR_ARGB8:4286419113")),
    MonetSemanticRule("theme.color.system-primary-light--system-primary-dark.slot-20", "color", setOf("config::literal:COLOR_ARGB8:4293899776")),
    MonetSemanticRule("theme.color.system-primary-light--system-primary-dark.slot-21", "color", setOf("config::literal:COLOR_ARGB8:4293899776")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-03", "color", setOf("config::literal:COLOR_RGB8:4293783021", "context:layout:attribute:LinearLayout/LinearLayout/TextView:16843000:layout_marginTop:DIMENSION:literal:DIMENSION:4294967041")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-06", "color", setOf("child:color:config::literal:COLOR_RGB8:4280295456", "child:color:outgoing:color", "adjacent:-1:config::reference:color:REFERENCE")),
    MonetSemanticRule("chat.bubble.incoming.pro", "drawable", setOf("adjacent:-2:attribute:selector/item:16842908:state_focused:BOOLEAN:literal:BOOLEAN:4294967295", "adjacent:1:attribute:selector/item:16842913:state_selected:BOOLEAN:literal:BOOLEAN:4294967295", "adjacent:2:attribute:selector/item:16843161:drawable:REFERENCE:reference:drawable:REFERENCE", "adjacent:-1:attribute:selector/item:16843161:drawable:REFERENCE:reference:drawable:REFERENCE")),
    MonetSemanticRule("chat.bubble.incoming.pro.handled", "drawable", setOf("adjacent:-1:attribute:selector/item:16842908:state_focused:BOOLEAN:literal:BOOLEAN:4294967295", "adjacent:2:attribute:selector/item:16842913:state_selected:BOOLEAN:literal:BOOLEAN:4294967295", "adjacent:1:attribute:selector/item:16842908:state_focused:BOOLEAN:literal:BOOLEAN:4294967295", "attribute:selector/item:16842908:state_focused:BOOLEAN:literal:BOOLEAN:4294967295")),
    MonetSemanticRule("chat.bubble.outgoing.pro", "drawable", setOf("adjacent:-1:attribute:selector/item:16842908:state_focused:BOOLEAN:literal:BOOLEAN:4294967295", "adjacent:1:attribute:selector/item:16842913:state_selected:BOOLEAN:literal:BOOLEAN:4294967295", "adjacent:-2:attribute:selector/item:16842908:state_focused:BOOLEAN:literal:BOOLEAN:4294967295", "attribute:selector/item:16843161:drawable:REFERENCE:reference:drawable:REFERENCE")),
    MonetSemanticRule("chat.bubble.outgoing.pro.handled", "drawable", setOf("adjacent:-1:attribute:selector/item:16842908:state_focused:BOOLEAN:literal:BOOLEAN:4294967295", "adjacent:-2:attribute:selector/item:16842913:state_selected:BOOLEAN:literal:BOOLEAN:4294967295", "attribute:selector/item:16843161:drawable:REFERENCE:reference:drawable:REFERENCE"), requiredAdjacentRoles = mapOf(-1 to "chat.bubble.outgoing.pro")),
    MonetSemanticRule("chat.red-envelope.incoming.alias", "drawable", setOf("adjacent:-2:attribute:shape:16843359:innerRadius:DIMENSION:literal:DIMENSION:1025", "adjacent:1:outgoing:drawable")),
    MonetSemanticRule("chat.red-envelope.outgoing.alias", "drawable", setOf("adjacent:2:attribute:shape/corners:16843176:radius:DIMENSION:literal:DIMENSION:5121", "attribute:selector/item:16842908:state_focused:BOOLEAN:literal:BOOLEAN:4294967295")),
    MonetSemanticRule("chat.transfer.incoming.expired", "drawable", setOf("attribute:selector/item:16842908:state_focused:BOOLEAN:literal:BOOLEAN:4294967295", "attribute:selector/item:16843161:drawable:REFERENCE:reference:drawable:REFERENCE")),
    MonetSemanticRule("chat.transfer.outgoing.expired", "drawable", setOf("attribute:selector/item:16842908:state_focused:BOOLEAN:literal:BOOLEAN:4294967295", "attribute:selector/item:16843161:drawable:REFERENCE:reference:drawable:REFERENCE")),
    MonetSemanticRule("chat.transfer.incoming.received", "drawable", setOf("attribute:selector/item:16842908:state_focused:BOOLEAN:literal:BOOLEAN:4294967295", "attribute:selector/item:16843161:drawable:REFERENCE:reference:drawable:REFERENCE")),
    MonetSemanticRule("chat.transfer.outgoing.received", "drawable", setOf("attribute:selector/item:16842908:state_focused:BOOLEAN:literal:BOOLEAN:4294967295", "attribute:selector/item:16843161:drawable:REFERENCE:reference:drawable:REFERENCE")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-13", "color", setOf("config::literal:COLOR_ARGB8:3437160959", "adjacent:-1:config::literal:COLOR_ARGB8:654311423")),
    MonetSemanticRule("theme.color.system-accent2-600--system-accent2-600.slot-02", "color", setOf("adjacent:-2:config:-night:literal:COLOR_ARGB8:3875010551")),
    MonetSemanticRule("theme.color.system-primary-light--system-primary-dark.slot-23", "color", setOf("adjacent:1:config::literal:COLOR_ARGB8:2149457438")),
    MonetSemanticRule("theme.color.system-primary-light--system-primary-dark.slot-25", "color", setOf("adjacent:-1:config::literal:COLOR_RGB8:4284661381")),
    MonetSemanticRule("theme.color.system-surface-container-dark--system-surface-container-dark.slot-07", "color", setOf("child:color:config::literal:COLOR_RGB8:4278190080", "child:color:config::literal:COLOR_RGB8:4278698336")),
    MonetSemanticRule("theme.color.system-surface-container-dark--system-surface-container-dark.slot-08", "color", setOf("adjacent:1:config::literal:COLOR_ARGB8:870353972")),
    MonetSemanticRule("theme.color.system-surface-container-dark--system-surface-container-dark.slot-13", "color", setOf("adjacent:2:config::literal:COLOR_RGB8:4278212427")),
    MonetSemanticRule("theme.color.system-surface-container-dark--system-surface-container-dark.slot-14", "color", setOf("adjacent:1:config::literal:COLOR_RGB8:4278212427")),
    MonetSemanticRule("theme.color.system-surface-container-dark--system-surface-container-dark.slot-20", "color", setOf("adjacent:2:config::literal:COLOR_ARGB8:3865404773")),
    MonetSemanticRule("theme.color.system-surface-container-light--10ffffff.slot-01", "color", setOf("adjacent:2:config:-night:literal:COLOR_ARGB8:872415231", "adjacent:2:config::literal:COLOR_ARGB8:4294967295")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-12", "color", setOf("adjacent:1:config::literal:COLOR_ARGB8:3437160959", "context:drawable:incoming:layout")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-16", "color", setOf("adjacent:-1:config::literal:COLOR_ARGB8:419430400", "adjacent:2:config::literal:COLOR_RGB8:4278698336")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-20", "color", setOf("adjacent:1:config::literal:COLOR_RGB8:4282927176")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-21", "color", setOf("adjacent:1:config::literal:COLOR_ARGB8:2147483647", "config::literal:COLOR_ARGB8:2147483648")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-22", "color", setOf("adjacent:1:config::literal:COLOR_RGB8:4283387727")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-24", "color", setOf("adjacent:2:config::literal:COLOR_RGB8:4280398080", "adjacent:-1:config::literal:COLOR_RGB8:4293848814")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-28", "color", setOf("adjacent:2:config::literal:COLOR_RGB8:4278252499")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-32", "color", setOf("config::literal:COLOR_ARGB8:1795162112", "adjacent:1:config::literal:COLOR_ARGB8:520093696")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-39", "color", setOf("adjacent:2:config:-night:literal:COLOR_ARGB8:4280163870", "adjacent:-1:config:-night:literal:COLOR_ARGB8:4279308561")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-41", "color", setOf("config:-night:literal:COLOR_ARGB8:4280163870", "adjacent:-1:config::literal:COLOR_ARGB8:4294440951")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-46", "color", setOf("adjacent:-1:config::literal:COLOR_ARGB8:436207616", "config::literal:COLOR_ARGB8:218103808")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-48", "color", setOf("adjacent:1:config:-night:literal:COLOR_ARGB8:3875010551")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-55", "color", setOf("adjacent:1:config::literal:COLOR_ARGB8:2164245029")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-light.slot-02", "color", setOf("adjacent:2:config::literal:COLOR_ARGB8:536870912", "adjacent:1:config::literal:COLOR_RGB8:4294967295")),
    MonetSemanticRule("theme.color.system-surface-dark--system-surface-dark.slot-04", "color", setOf("adjacent:-2:config::literal:COLOR_ARGB8:4282861383")),
    MonetSemanticRule("theme.color.system-surface-dark--system-surface-dark.slot-07", "color", setOf("config::literal:COLOR_RGB8:4294926662", "adjacent:2:config::reference:color:REFERENCE", "adjacent:1:config::reference:color:REFERENCE")),
    MonetSemanticRule("theme.color.system-surface-dark--system-surface-dark.slot-14", "color", setOf("context:style:outgoing:raw", "adjacent:1:config::reference:color:REFERENCE", "adjacent:-1:config::reference:color:REFERENCE")),
    MonetSemanticRule("theme.color.system-surface-light--system-surface-dark.slot-05", "color", setOf("adjacent:2:config::literal:COLOR_ARGB8:870353972")),
    MonetSemanticRule("theme.color.system-surface-light--system-surface-dark.slot-09", "color", setOf("adjacent:1:config:-night:literal:COLOR_ARGB8:4280295456", "config:-night:literal:COLOR_ARGB8:4279834905")),
    MonetSemanticRule("theme.color.system-surface-light--system-surface-light.slot-02", "color", setOf("adjacent:2:config::literal:COLOR_RGB8:4279769112")),
    MonetSemanticRule("theme.color.unknown--10ffffff.slot-02", "color", setOf("context:layout:attribute:LinearLayout/ImageView:16842997:layout_height:DIMENSION:literal:DIMENSION:6401", "adjacent:1:config::reference:color:REFERENCE")),
    MonetSemanticRule("theme.color.unknown--10ffffff.slot-03", "color", setOf("adjacent:1:config:-night:literal:COLOR_ARGB8:872415231", "adjacent:2:config::reference:color:REFERENCE")),
    MonetSemanticRule("theme.color.unknown--10ffffff.slot-05", "color", setOf("adjacent:2:config::literal:COLOR_ARGB8:234881023", "adjacent:1:config::literal:COLOR_ARGB8:3875536895")),
    MonetSemanticRule("theme.color.system-surface-container-light--10ffffff.slot-02", "color", emptySet()),
    MonetSemanticRule("theme.color.system-surface-container-light--10ffffff.slot-03", "color", setOf("simple-usage:layout:ConstraintLayout/RoundCornerLinearLayout:16842964:background")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-37", "color", setOf("child:color:config::literal:COLOR_ARGB8:3841982464", "config::reference:color:REFERENCE"), preferredEvidence = setOf("config::reference:color:REFERENCE", "child:color:config:-night:literal:COLOR_ARGB8:3439329279", "outgoing:color", "child:color:config::literal:COLOR_ARGB8:3841982464")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-47", "color", setOf("adjacent:-2:config::literal:COLOR_ARGB8:436207616"), preferredEvidence = setOf("adjacent:-2:config::literal:COLOR_ARGB8:436207616", "config::literal:COLOR_RGB8:4294440951", "config:-night:literal:COLOR_RGB8:4281479730", "adjacent:-1:config::literal:COLOR_ARGB8:218103808")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-50", "color", emptySet()),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-53", "color", setOf("adjacent:-1:config::literal:COLOR_ARGB8:872415231"), preferredEvidence = setOf("adjacent:-1:config::literal:COLOR_ARGB8:872415231", "adjacent:1:config::literal:COLOR_ARGB8:638042464", "config::literal:COLOR_RGB8:4278698336", "adjacent:2:config::literal:COLOR_RGB8:4293783021")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-56", "color", setOf("context:drawable:element:shape/corners", "context:drawable:element:shape/solid")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-57", "color", emptySet(), optional = true),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-58", "color", setOf("context:drawable:attribute:shape/corners:16843176:radius:DIMENSION:literal:DIMENSION:1025", "context:drawable:usage:layout:LinearLayout:16842964:background")),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-59", "color", emptySet()),
    MonetSemanticRule("theme.color.system-surface-container-light--system-surface-container-dark.slot-60", "color", emptySet(), preferredEvidence = setOf("config::literal:COLOR_ARGB8:4294440951", "adjacent:-1:config::literal:COLOR_ARGB8:2348810240", "adjacent:1:config::literal:COLOR_RGB8:4292854676", "adjacent:2:config::literal:COLOR_ARGB8:3439329279")),
    MonetSemanticRule("theme.color.system-surface-dark--system-surface-dark.slot-02", "color", emptySet()),
    MonetSemanticRule("theme.color.system-surface-light--system-surface-dark.slot-04", "color", emptySet()),
    MonetSemanticRule("main.surface.header.primary", "drawable", setOf("config::file:9PNG:21:190:0:47:56:1015182:1017450:2:259089148f46db80af657aa18439589603c0807cd88376e29026eeda003fcaab")),
    MonetSemanticRule("main.surface.header.secondary", "drawable", setOf("config::file:9PNG:21:190:0:47:56:98742:1017450:2:f6ff144aac212eb90c20f65bd2d5b481271e46432e5712f0b03a6af21d87d096")),
)
